version: "3.9"
services:
  postgres-demo:
    container_name: postgres-demo
    image: postgres:17.2-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres-demo
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PORT: ${DB_PORT}
      TZ: ${DB_TIMEZONE}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - dev_network
    volumes:
      - goeb_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
        reservations:
          cpus: "0.25"
          memory: "256M"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${DB_USER} -d $${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  dev_network:
    name: dev_network

volumes:
  goeb_data:
    name: goeb_data
